version: "3.9"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=$PGPASSWORD
      - POSTGRES_USER=$PGUSER
      - POSTGRES_DB=$PGDATABASE
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - 3030:8080

